eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
  instance:
    hostname: "${HOSTNAME}.${SERVICE_NAME}"
server:
  port: 8761
spring:
  application:
    name: EUREKA-SERVER
