version: "3.7"
services:

#Eureka Server
 EUREKA-SERVER:
  image: r2553/eureka-server:latest
  container_name: EUREKA-SERVER
  pull_policy: always
  ports:
   - "8761:8761"
  environment:
   - SPRING_PROFILES_ACTIVE=docker
  restart: on-failure
 
#Api Gateway
 API-GATEWAY:
  image: r2553/api-gateway:latest
  container_name: API-GATEWAY
  pull_policy: always
  ports:
  - "9090:9090"
  depends_on:
  - EUREKA-SERVER
  environment:
   - SPRING_PROFILES_ACTIVE=docker
  restart: on-failure
  
#Authentication
 AUTHENTICATION-SERVICE:
  image: r2553/authentication:latest
  container_name: AUTHENTICATION-SERVICE
  pull_policy: always
  ports:
  - "7771:7771"
  depends_on:
  - EUREKA-SERVER
  - API-GATEWAY
  - DB
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - MYSQL_HOST=DB
   - MYSQL_PORT=3306
   - MYSQL_USERNAME=root
   - MYSQL_PASSWORD=root
  restart: always
  
#MySQL volumes_from:
 DB:
    image: mysql
    container_name: DB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3307:3306" 
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: